// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/smartphone.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SmartphoneService_GetOne_FullMethodName  = "/smartphone.SmartphoneService/GetOne"
	SmartphoneService_GetMany_FullMethodName = "/smartphone.SmartphoneService/GetMany"
)

// SmartphoneServiceClient is the client API for SmartphoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartphoneServiceClient interface {
	GetOne(ctx context.Context, in *OneRequest, opts ...grpc.CallOption) (*OneResponse, error)
	GetMany(ctx context.Context, in *ManyRequest, opts ...grpc.CallOption) (*ManyResponse, error)
}

type smartphoneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartphoneServiceClient(cc grpc.ClientConnInterface) SmartphoneServiceClient {
	return &smartphoneServiceClient{cc}
}

func (c *smartphoneServiceClient) GetOne(ctx context.Context, in *OneRequest, opts ...grpc.CallOption) (*OneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OneResponse)
	err := c.cc.Invoke(ctx, SmartphoneService_GetOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartphoneServiceClient) GetMany(ctx context.Context, in *ManyRequest, opts ...grpc.CallOption) (*ManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManyResponse)
	err := c.cc.Invoke(ctx, SmartphoneService_GetMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartphoneServiceServer is the server API for SmartphoneService service.
// All implementations must embed UnimplementedSmartphoneServiceServer
// for forward compatibility.
type SmartphoneServiceServer interface {
	GetOne(context.Context, *OneRequest) (*OneResponse, error)
	GetMany(context.Context, *ManyRequest) (*ManyResponse, error)
	mustEmbedUnimplementedSmartphoneServiceServer()
}

// UnimplementedSmartphoneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmartphoneServiceServer struct{}

func (UnimplementedSmartphoneServiceServer) GetOne(context.Context, *OneRequest) (*OneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedSmartphoneServiceServer) GetMany(context.Context, *ManyRequest) (*ManyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMany not implemented")
}
func (UnimplementedSmartphoneServiceServer) mustEmbedUnimplementedSmartphoneServiceServer() {}
func (UnimplementedSmartphoneServiceServer) testEmbeddedByValue()                           {}

// UnsafeSmartphoneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartphoneServiceServer will
// result in compilation errors.
type UnsafeSmartphoneServiceServer interface {
	mustEmbedUnimplementedSmartphoneServiceServer()
}

func RegisterSmartphoneServiceServer(s grpc.ServiceRegistrar, srv SmartphoneServiceServer) {
	// If the following call pancis, it indicates UnimplementedSmartphoneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SmartphoneService_ServiceDesc, srv)
}

func _SmartphoneService_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartphoneServiceServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartphoneService_GetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartphoneServiceServer).GetOne(ctx, req.(*OneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartphoneService_GetMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartphoneServiceServer).GetMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartphoneService_GetMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartphoneServiceServer).GetMany(ctx, req.(*ManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartphoneService_ServiceDesc is the grpc.ServiceDesc for SmartphoneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartphoneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartphone.SmartphoneService",
	HandlerType: (*SmartphoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _SmartphoneService_GetOne_Handler,
		},
		{
			MethodName: "GetMany",
			Handler:    _SmartphoneService_GetMany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/smartphone.proto",
}
